### ISSUE TITLE
Task/Missions to earn Exp

### ISSUE THREAD

**Issue by TrentMeddings** [ConnorMc27/LifestyleRPG#6]
1. Exercise 
2. Homework

Add more

**Comment by ConnorMc27** [comment]
When someone logs on they get asked to enter a task or 2.
This task is then anonymously sent to someone else using the app, the amount of xp for the reward can be determined by your own level and how reliable you are seen to be over time. though in the end it is dependent on trust because the only people affected by trolling are the people themselves.
The task will also only be sent to another person within your level range

**Comment by ConnorMc27** [comment]
the amount of currency that can be rewarded follows the same rules, but has a limitation.

Some sort of limitation needs to be put in place to prevent people setting extremely high rewards. such as a person being required to take a picture to prove completion, if applicable to the task, and the tasks having to go through community viewing in which people look at tasks and collectively approve or disprove the completion
